name:                simplex-definitions
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/simplex-chat/protocol/blob/master/definitions/readme.md
license:             AGPL-3
author:              Evgeny Poberezkin
copyright:           2020 Evgeny Poberezkin
category:            Web
extra-source-files:
- readme.md

ghc-options:
  - -Wall
  - -Wcompat
  - -Werror=incomplete-patterns
  - -Wredundant-constraints
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns

default-extensions:
  - TemplateHaskell
  - NoImplicitPrelude
  # numbers, strings, lists
  - NegativeLiterals
  - NumericUnderscores
  - OverloadedStrings
  # function syntax
  - BlockArguments
  - EmptyCase
  - LambdaCase
  # Records
  - DuplicateRecordFields
  - NamedFieldPuns
  - RecordWildCards
  # deriving
  - DeriveAnyClass
  - DeriveFunctor
  - DeriveGeneric
  - StandaloneDeriving
  # type classes
  - FunctionalDependencies
  - FlexibleContexts
  - FlexibleInstances
  - InstanceSigs
  - TypeSynonymInstances
  - UndecidableInstances
  # types
  - DataKinds
  - ConstraintKinds
  - GADTs
  - KindSignatures
  - LiberalTypeSynonyms
  - NoStarIsType
  - PolyKinds
  - RankNTypes
  - ScopedTypeVariables
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  
dependencies:
  - aeson
  - base >= 4.7 && < 5
  - classy-prelude
  - decidable
  - lens
  - singletons
  - servant-docs
  - servant-server

library:
  source-dirs: src
  exposed-modules:
    - Simplex.Messaging.Types
    - Simplex.Messaging.ServerAPI

executables:
  api-docs:
    source-dirs:      src
    main:             Main.hs
