name: simplexmq
description: A starting point for Dart libraries or applications.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  asn1lib: ^1.0.2
  pointycastle:
    git:
      url: https://github.com/simplex-chat/pc-dart.git
      ref: nullsafety

  # pointycastle: ^3.3.4

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
